### ISSUE TITLE
GCC 11.2.0 [-Werror=nonnull]

### ISSUE THREAD

**Issue by nyckmaia** [boostorg/concept_check#36] opened 2022-04-07 19:14 UTC
My current C++ code compiles without any warnings using GCC 7.3 or 10.2.

Now, I switch to GCC 11.2.0 and the same code gives me a set of this message below:

```
error: 'this' pointer is null [-Werror=nonnull]

In file included from C:\dev\evo-pos\submodules\evo-tef-client\submodules\cpp-third-party-libs\windows\amd64\boost-1.68.0\include/boost/concept/assert.hpp:35,
                 from C:\dev\evo-pos\submodules\evo-tef-client\submodules\cpp-third-party-libs\windows\amd64\boost-1.68.0\include/boost/concept_check.hpp:20,
                 from C:\dev\evo-pos\submodules\evo-tef-client\submodules\cpp-third-party-libs\windows\amd64\boost-1.68.0\include/boost/range/concepts.hpp:19,
                 from C:\dev\evo-pos\submodules\evo-tef-client\submodules\cpp-third-party-libs\windows\amd64\boost-1.68.0\include/boost/range/size_type.hpp:20,
                 from C:\dev\evo-pos\submodules\evo-tef-client\submodules\cpp-third-party-libs\windows\amd64\boost-1.68.0\include/boost/range/size.hpp:21,
                 from C:\dev\evo-pos\submodules\evo-tef-client\submodules\cpp-third-party-libs\windows\amd64\boost-1.68.0\include/boost/range/functions.hpp:20,
                 from C:\dev\evo-pos\submodules\evo-tef-client\submodules\cpp-third-party-libs\windows\amd64\boost-1.68.0\include/boost/range/iterator_range_core.hpp:38,
                 from C:\dev\evo-pos\submodules\evo-tef-client\submodules\cpp-third-party-libs\windows\amd64\boost-1.68.0\include/boost/range/iterator_range.hpp:13,
                 from C:\dev\evo-pos\submodules\evo-tef-client\submodules\cpp-third-party-libs\windows\amd64\boost-1.68.0\include/boost/range/as_literal.hpp:22,
                 from C:\dev\evo-pos\submodules\evo-tef-client\submodules\cpp-third-party-libs\windows\amd64\boost-1.68.0\include/boost/algorithm/string/trim.hpp:19,
                 from C:\dev\evo-pos\submodules\evo-tef-client\submodules\cpp-third-party-libs\windows\amd64\boost-1.68.0\include/boost/algorithm/string.hpp:19,
                 from C:\dev\evo-pos\src\evopos\core\remote_transactions\remote_transactions_screens.cpp:18:
C:\dev\evo-pos\submodules\evo-tef-client\submodules\cpp-third-party-libs\windows\amd64\boost-1.68.0\include/boost/concept/detail/general.hpp: In instantiation of 'static void boost::concepts::constraint<Model>::failed() [with Model = boost::algorithm::FinderConcept<boost::algorithm::detail::token_finderF<boost::algorithm::detail::is_any_ofF<char> >, __gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char> > >]':
C:\dev\evo-pos\submodules\evo-tef-client\submodules\cpp-third-party-libs\windows\amd64\boost-1.68.0\include/boost/algorithm/string/iter_find.hpp:77:13:   required from 'SequenceSequenceT& boost::algorithm::iter_split(SequenceSequenceT&, RangeT&, FinderT) [with SequenceSequenceT = std::vector<std::__cxx11::basic_string<char> >; RangeT = std::__cxx11::basic_string<char>; FinderT = boost::algorithm::detail::token_finderF<boost::algorithm::detail::is_any_ofF<char> >]'
C:\dev\evo-pos\submodules\evo-tef-client\submodules\cpp-third-party-libs\windows\amd64\boost-1.68.0\include/boost/algorithm/string/split.hpp:146:50:   required from 'SequenceSequenceT& boost::algorithm::split(SequenceSequenceT&, RangeT&, PredicateT, boost::algorithm::token_compress_mode_type) [with SequenceSequenceT = std::vector<std::__cxx11::basic_string<char> >; RangeT = std::__cxx11::basic_string<char>; PredicateT = boost::algorithm::detail::is_any_ofF<char>]'
C:\dev\evo-pos\src\evopos\core\remote_transactions\remote_transactions_screens.cpp:261:17:   required from here
C:\dev\evo-pos\submodules\evo-tef-client\submodules\cpp-third-party-libs\windows\amd64\boost-1.68.0\include/boost/concept/detail/general.hpp:47:52: error: 'this' pointer is null [-Werror=nonnull]
   47 |     static void failed() { ((Model*)0)->constraints(); }
      |                            ~~~~~~~~~~~~~~~~~~~~~~~~^~
```

My system:
- Windows 11 x64
- Compiler: G++ 11.2.0 (MSYS2)
- Boost: 1.68.0
- C++ standard flag: `-std=c++0x`

**Comment by mclow** [comment] 2022-04-07 21:12
Duplicate of https://github.com/boostorg/concept_check/issues/27, was fixed I'm Arch, will be part of Boost 1.79.0

**Closed by mclow** 2022-04-07 21:12 UTC
